version: "3"

services:
    mongo:
        image: mongo:latest
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: parkyeung
            MONGO_INITDB_ROOT_PASSWORD: parkyeung
        ports:
            - 27017:27017
        volumes:
            - ./_docker/apibara_mongodb:/data/db

    indexer:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        command:
            - start
            - --mongo-url
            - "mongodb+srv://parkyeung:parkyeung@starkdexindexer.5ypmk.mongodb.net"
        environment:
            PYTHONUNBUFFERED: "1"
        links:
            - mongo
